SOURCE_EXTENSION = ".ant"
SOURCE_EXTENSION_REGEX = f"*{SOURCE_EXTENSION}"
C_ACC_LIBRARY_EXTENSION_REGEX = "*.c"

SOURCE_DESCRIPTION = "AnteaterLang Source"
C_ACC_LIBRARY_EXTENSION_DESCRIPTION = "C Acc Library Source"

TERMINAL_BACKGROUND_COLOR = '#2B2B2B'
EDITOR_BACKGROUND_COLOR = '#2B2B2B'

TERMINAL_FONT_SIZE = 15
EDITOR_FONT_SIZE = 15
TAB_SPACE = 4

IDE_PROJECT_SETTING_NAME = "/ideconfig.pickle"

DEFAULT_WINDOW_SIZE = "1600x800"

ANTEATERLANG_KEYWORD = "antlang"

C_ACC_LIBRARY_SO_PATH = "libuserFunctions.so"

IDE_VERSION = "0.1.0"
